apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: kaniko-template
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
      default: "uk.icr.io/cameron-guest/kaniko-chains"
    - name: DOCKERCONFIG
      description: Docker config JSON for image
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      data:
        .dockerconfigjson: $(tt.params.DOCKERCONFIG)
      metadata:
        name: registry-credentials
      type: kubernetes.io/dockerconfigjson
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: kaniko-run-
      spec:
        pipelineRef:
          name: kaniko-pipeline
        workspaces:
          - name: pipeline-ws1
            emptyDir: {}
          - name: pipeline-ws2
            secret:
              secretName: registry-credentials
        params:
          - name: IMAGE
            value: $(tt.params.IMAGE)
        podTemplate:
          imagePullSecrets:
            - name: registry-credentials
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: kaniko-binding
spec:
  params:
    - name: IMAGE
      value: $(body.IMAGE)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: kaniko-listener
spec:
  triggers:
    - name: kaniko-trigger
      bindings:
        - ref: kaniko-binding
      template:
        ref: kaniko-template