apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
  workspaces:
    - name: pipeline-ws1
    - name: pipeline-ws2
  tasks:
    - name: build-image
      taskRef:
        name: kaniko-chains
      workspaces:
        - name: source
          workspace: pipeline-ws1
        - name: dockerconfig
          workspace: pipeline-ws2
      params:
        - name: IMAGE
          value: $(params.IMAGE)