apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
  tasks:
    - name: build-image
      taskRef:
        name: kaniko-chains
      params:
        - name: IMAGE
          value: $(params.IMAGE)